service: MQR
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-west-1
  memorySize: 128
  apiGateway:
    binaryMediaType:
      - "*/*"
functions:
  app:
    handler: src/server.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
